import type { Funcionario } from '../types';

type OperationalDriverSeed = readonly [matricula: string, nome: string, cargo: string];

const OPERATIONAL_DRIVER_SEEDS: readonly OperationalDriverSeed[] = [
  ['103177', 'ADILSON PIRES DA CRUZ', 'OPERADOR DE CAMINHAO BASCULANTE'],
  ['102507', 'ALEXANDRE DOS SANTOS RODRIGUES', 'OPERADOR DE CARRETA'],
  ['101671', 'ANDERSON PEIXOTO DA SILVA', 'OPERADOR DE CAMINHAO BASCULANTE'],
  ['103038', 'APARECIDO MEIRA DA SILVA', 'OPERADOR DE CAMINHAO BASCULANTE'],
  ['102512', 'ARENILSON TEIXEIRA DOS SANTOS', 'OPERADOR DE CAMINHAO BASCULANTE'],
  ['101788', 'CELSON SIQUEIRA SILVA', 'OPERADOR DE CAMINHAO BASCULANTE'],
  ['102146', 'EDMILSON ALVES DA SILVA', 'OPERADOR DE CAMINHAO BASCULANTE'],
  ['102022', 'EDUARDO SOARES DE OLIVEIRA', 'OPERADOR DE CAMINHAO BASCULANTE'],
  ['102863', 'ELADIO COSTA SILVA', 'OPERADOR DE CAMINHAO BASCULANTE'],
  ['101564', 'EUDES DOS SANTOS MATHEUS', 'OPERADOR DE CAMINHAO BASCULANTE'],
  ['102112', 'EZEQUIEL DE SOUZA VIEIRA', 'OPERADOR DE CAMINHAO BASCULANTE'],
  ['101990', 'FABIANO ALVES NUNES', 'OPERADOR DE CAMINHAO BASCULANTE'],
  ['102023', 'GENIVALDO MANOEL DOS SANTOS', 'OPERADOR DE CAMINHAO BASCULANTE'],
  ['102148', 'GLEISSON SANTOS DE JESUS', 'OPERADOR DE CAMINHAO BASCULANTE'],
  ['102861', 'HELIO EVARISTO LUCAS', 'OPERADOR DE CAMINHAO BASCULANTE'],
  ['102102', 'HUMBERTO RIBEIRO COELHO', 'OPERADOR DE CAMINHAO BASCULANTE'],
  ['101565', 'JEAM OLIVEIRA DA SILVA', 'OPERADOR DE CAMINHÃO PIPA'],
  ['102016', 'JOSE APARECIDO FIRMINO', 'OPERADOR DE CAMINHAO BASCULANTE'],
  ['103174', 'JOSE RICARDO GARCIA', 'OPERADOR DE CAMINHAO BASCULANTE'],
  ['102865', 'JOSIAS LIMA DE ARAUJO', 'OPERADOR DE CAMINHAO BASCULANTE'],
  ['103109', 'JOSUE XAVIER FRANCISCO', 'OPERADOR DE CAMINHAO BASCULANTE'],
  ['102514', 'MANOEL MENDES COUTINHO', 'OPERADOR DE CAMINHAO BASCULANTE'],
  ['102064', 'NELSON TADEU DOS SANTOS', 'OPERADOR DE CAMINHAO BASCULANTE'],
  ['102939', 'RICARDO ALVES DOS SANTOS JUNIOR', 'OPERADOR DE CAMINHAO BASCULANTE'],
  ['102515', 'RICARDO DE BARROS', 'OPERADOR DE CAMINHÃO PIPA'],
  ['102928', 'RODRIGO SOARES SALDANHA', 'OPERADOR DE CAMINHAO BASCULANTE'],
  ['102147', 'RONALDO SOARES DE OLIVEIRA', 'OPERADOR DE CAMINHAO BASCULANTE'],
  ['102513', 'SAMUEL PEREIRA DOS SANTOS', 'OPERADOR DE CAMINHAO BASCULANTE'],
  ['102868', 'THIAGO FELIPE SPAMPINATO PRADO', 'OPERADOR DE CAMINHAO BASCULANTE'],
  ['101979', 'WEDLEY PEREIRA DOS SANTOS', 'OPERADOR DE CAMINHAO BASCULANTE'],
  ['102153', 'WILSON FLORENTINO RITI', 'OPERADOR DE CAMINHAO BASCULANTE'],
  ['102018', 'JOSE ALLAN KARDEC DA SILVA', 'OPERADOR DE CAMINHAO BASCULANTE'],
  ['103206', 'EDUARDO ROMUALDO DA SILVA', 'OPERADOR DE CAMINHAO BASCULANTE'],
  ['103240', 'JACONIAS ALVES DE OLIVEIRA', 'OPERADOR DE CAMINHAO BASCULANTE'],
  ['103241', 'ROGERIO DA SILVA RASPANTE', 'OPERADOR DE CAMINHAO BASCULANTE'],
];

/** Cadastro exclusivo do Controle Operacional de Frotas, sem duplicação em colaboradores. */
export const OPERATIONAL_DRIVERS: readonly Funcionario[] = OPERATIONAL_DRIVER_SEEDS.map(
  ([matricula, nome, cargo]) => ({
    id: `motorista-operacional-${matricula}`,
    matricula,
    nome,
    cargo,
    telefone: '',
    empresaId: 'emp-1',
    ativo: true,
    status: 'ATIVO',
    area: 'FROTAS OPERACIONAIS',
    divisao: 'OPERAÇÃO',
    observacao: 'Cadastro exclusivo do Controle Operacional de Frotas.',
  }),
);

export const OPERATIONAL_DRIVER_COUNT = OPERATIONAL_DRIVERS.length;
