import type { PresencaApontamento } from '../types';
import type { MaterialUseSubmission } from '../modules/materials/materialFieldUse';
import { getSupabaseClient } from './client';

export const SUBMISSIONS_COLLECTION = 'erp_public_submissions';
export type PublicSubmission = { id: string; kind: 'presence' | 'presence-reset' | 'equipe'; status: 'pending' | 'processed' | 'cancelled'; createdAtIso: string; payload: { grupoId?: string; grupoNome?: string; data: string; records?: PresencaApontamento[]; funcionarioId?: string; funcionarioNome?: string; funcao?: string; operacao?: 'adicionar' | 'remover' } };
type Row = { id: string; kind: string; status: string; created_at: string; payload: PublicSubmission['payload'] };
export const normalizeSubmissionRows = (rows: Row[]): PublicSubmission[] => rows.map(item => ({ id: item.id, kind: item.kind, status: item.status, createdAtIso: item.created_at, payload: item.payload } as PublicSubmission)).filter(item => ['presence', 'presence-reset', 'equipe'].includes(item.kind)).filter(item => item.payload && typeof item.payload.data === 'string').sort((a, b) => a.createdAtIso.localeCompare(b.createdAtIso));
const pending = async () => { const { data, error } = await getSupabaseClient().from(SUBMISSIONS_COLLECTION).select('id,kind,status,created_at,payload').eq('status', 'pending').order('created_at', { ascending: true }); if (error) throw error; return (data || []) as Row[]; };
export const subscribePendingPublicSubmissions = (_database: unknown, onChange: (items: PublicSubmission[]) => void, onError: (error: Error) => void) => { let active = true; const refresh = async () => { try { if (active) onChange(normalizeSubmissionRows(await pending())); } catch (error) { onError(error as Error); } }; void refresh(); const channel = getSupabaseClient().channel('erp-public-submissions').on('postgres_changes', { event: '*', schema: 'public', table: SUBMISSIONS_COLLECTION }, () => void refresh()).subscribe(); return () => { active = false; void getSupabaseClient().removeChannel(channel); }; };
export const markPublicSubmissionsProcessed = async (_database: unknown, ids: string[], processedBy: string) => { const { error } = await getSupabaseClient().from(SUBMISSIONS_COLLECTION).update({ status: 'processed', processed_at: new Date().toISOString(), processed_by: processedBy }).in('id', ids); if (error) throw error; };
export const subscribePendingMaterialUses = (_database: unknown, onChange: (items: MaterialUseSubmission[]) => void, onError: (error: Error) => void) => { let active = true; const refresh = async () => { try { const rows = await pending(); const items = rows.filter(item => item.kind === 'material-uso').map(item => ({ id: item.id, ...item.payload } as unknown as MaterialUseSubmission)); if (active) onChange(items); } catch (error) { onError(error as Error); } }; void refresh(); const channel = getSupabaseClient().channel('erp-material-submissions').on('postgres_changes', { event: '*', schema: 'public', table: SUBMISSIONS_COLLECTION }, () => void refresh()).subscribe(); return () => { active = false; void getSupabaseClient().removeChannel(channel); }; };
