/** Painel executivo do ERP RENEA: ambiente operacional, com dados reais. */
import { useMemo, useRef, useState } from 'react';
import gsap from 'gsap';
import { useGSAP } from '@gsap/react';
import { AlertTriangle, CalendarDays, ChevronDown, ChevronRight, ClipboardCheck, Clock3, Droplets, FileText, RefreshCw, ShieldAlert, Truck, Users, Wrench } from 'lucide-react';
import type { Abastecimento, ApontamentoRamo, ApontamentoRamoRegistro, Comboio, ControleEstacas, Empresa, Equipamento, Funcionario, HistoryLog, ListaPresenca, Lubrificacao, MaterialRegistro, ObraLocal, OrdemServico, ParteDiariaEquipamento, PresencaApontamento, ProdutoLubrificacao, TicketJazida, TipoCombustivel } from '../types';
import { getOperationalFuelLiters, splitOperationalFuelRecords } from '../utils/fuelAnalyticsSafety';

interface DashboardProps {
  empresas: Empresa[]; obras: ObraLocal[]; equipamentos: Equipamento[]; funcionarios: Funcionario[]; comboios: Comboio[]; combustiveis: TipoCombustivel[]; lubrificantes: ProdutoLubrificacao[]; abastecimentos: Abastecimento[]; lubrificacoes: Lubrificacao[]; historyLogs: HistoryLog[]; listasPresenca?: ListaPresenca[]; ordensServico?: OrdemServico[]; ticketsJazida?: TicketJazida[]; estacas?: ControleEstacas; presencasLink?: PresencaApontamento[]; apontamentoRamos?: ApontamentoRamo[]; apontamentoRamoRegistros?: ApontamentoRamoRegistro[]; materiaisRegistros?: MaterialRegistro[]; partesDiariasEquipamentos?: ParteDiariaEquipamento[]; onNavigate: (tab: string) => void;
}
const formatNumber = new Intl.NumberFormat('pt-BR');
const formatLiters = new Intl.NumberFormat('pt-BR', { maximumFractionDigits: 0 });
const attendees = (list: ListaPresenca) => Array.isArray(list.funcionarios) ? list.funcionarios : [];

export default function Dashboard({ obras, equipamentos, funcionarios, abastecimentos, historyLogs, listasPresenca = [], ordensServico = [], onNavigate }: DashboardProps) {
  const [showDetails, setShowDetails] = useState(false);
  const dashboardRef = useRef<HTMLDivElement>(null);
  const today = new Date().toISOString().slice(0, 10);
  const formattedToday = new Intl.DateTimeFormat('pt-BR', { day: '2-digit', month: '2-digit', year: 'numeric' }).format(new Date());
  const overview = useMemo(() => {
    const { operational, review } = splitOperationalFuelRecords(abastecimentos);
    const totalLiters = operational.reduce((total, row) => total + (getOperationalFuelLiters(row) || 0), 0);
    const active = equipamentos.filter(item => item.status === 'Ativo' || item.status === 'Mobilizado').length;
    const maintenance = equipamentos.filter(item => item.status === 'Manutenção').length;
    const waitingDriver = equipamentos.filter(item => item.status === 'Esperando motorista').length;
    const available = waitingDriver;
    const openOrders = ordensServico.filter(item => ['Aberta', 'Em Andamento', 'Aguardando Peça'].includes(item.status));
    const urgentOrders = openOrders.filter(item => item.prioridade === 'Urgente');
    const activeWorks = obras.filter(item => item.status === 'Ativa');
    const worksWithoutAttendance = activeWorks.filter(work => !listasPresenca.some(list => list.obraId === work.id && list.data === today));
    const latestLists = activeWorks.map(work => listasPresenca.filter(list => list.obraId === work.id).sort((a, b) => b.data.localeCompare(a.data))[0]).filter((item): item is ListaPresenca => Boolean(item));
    const peopleListed = latestLists.reduce((total, list) => total + attendees(list).length, 0);
    const peoplePresent = latestLists.reduce((total, list) => total + attendees(list).filter(person => person.presente).length, 0);
    const fuelByFleet = Array.from(operational.reduce((map, row) => {
      const equipment = equipamentos.find(item => item.id === row.equipamentoId);
      const key = equipment?.id || row.prefixoInformado || 'sem-prefixo';
      const existing = map.get(key) || { prefix: equipment?.prefixo || row.prefixoInformado || 'Sem prefixo', name: equipment?.nome || 'Cadastro pendente', liters: 0 };
      existing.liters += getOperationalFuelLiters(row) || 0; map.set(key, existing); return map;
    }, new Map<string, { prefix: string; name: string; liters: number }>()).values()).sort((a, b) => b.liters - a.liters).slice(0, 5);
    const teamsInField = Math.max(0, activeWorks.length - worksWithoutAttendance.length);
    const recordsToday = operational.filter(row => row.data === today).length;
    return { totalLiters, active, maintenance, waitingDriver, available, openOrders: openOrders.length, urgentOrders: urgentOrders.length, fuelReview: review.length, worksWithoutAttendance, peopleListed, peoplePresent, fuelByFleet, teamsInField, recordsToday };
  }, [abastecimentos, equipamentos, ordensServico, obras, listasPresenca, today]);
  const presenceRate = overview.peopleListed ? Math.round((overview.peoplePresent / overview.peopleListed) * 100) : 0;
  const equipmentAvailability = equipamentos.length ? Math.round(((overview.active + overview.available) / equipamentos.length) * 100) : 0;
  const alerts = [
    ...(overview.urgentOrders ? [{ id: 'urgent-os', tone: 'danger' as const, title: `${overview.urgentOrders} ordem(ns) de serviço urgente(s)`, detail: 'Priorize a avaliação dos equipamentos críticos.', badge: overview.urgentOrders, tab: 'controle-equipamentos' }] : []),
    ...(overview.waitingDriver ? [{ id: 'operators', tone: 'warning' as const, title: 'Equipamentos aguardando operador', detail: 'Verifique a escala para evitar indisponibilidade.', badge: overview.waitingDriver, tab: 'controle-equipamentos' }] : []),
    ...(overview.worksWithoutAttendance.length ? [{ id: 'attendance', tone: 'info' as const, title: 'Equipes sem presença hoje', detail: overview.worksWithoutAttendance.slice(0, 2).map(item => item.nome).join(' · '), badge: overview.worksWithoutAttendance.length, tab: 'presenca' }] : []),
    ...(overview.fuelReview ? [{ id: 'fuel', tone: 'warning' as const, title: 'Abastecimentos para conferência', detail: 'Os registros foram preservados e aguardam revisão.', badge: overview.fuelReview, tab: 'lancamentos' }] : []),
    ...(overview.maintenance ? [{ id: 'maintenance', tone: 'neutral' as const, title: 'Equipamentos em manutenção', detail: 'Acompanhe liberação, oficina e horas paradas.', badge: overview.maintenance, tab: 'controle-equipamentos' }] : []),
  ];
  const metrics = [
    { label: 'Equipamentos ativos', value: formatNumber.format(overview.active), note: `${formatNumber.format(equipamentos.length)} cadastrados`, icon: ClipboardCheck },
    { label: 'Equipes em campo', value: formatNumber.format(overview.teamsInField), note: `${obras.filter(item => item.status === 'Ativa').length} frente(s) ativa(s)`, icon: Users },
    { label: 'Ordens de serviço abertas', value: formatNumber.format(overview.openOrders), note: overview.urgentOrders ? `${overview.urgentOrders} urgente(s)` : 'Nenhuma urgente', icon: Wrench },
    { label: 'Atendimentos hoje', value: formatNumber.format(overview.recordsToday), note: 'Lançamentos operacionais', icon: Clock3 },
  ];
  useGSAP(() => {
    if (window.matchMedia('(prefers-reduced-motion: reduce)').matches || !dashboardRef.current) return;
    gsap.fromTo(dashboardRef.current.querySelectorAll('[data-erp-enter]'), { autoAlpha: 0, y: 12 }, { autoAlpha: 1, y: 0, duration: 0.38, stagger: 0.045, ease: 'power2.out', clearProps: 'transform,opacity,visibility' });
  }, { scope: dashboardRef, dependencies: [overview.active, overview.openOrders, historyLogs.length] });
  return <div ref={dashboardRef} id="dashboard-tab" className="erp-dashboard min-h-full w-full bg-[#f7f9fa] px-5 pb-12 pt-8 sm:px-7 lg:px-9 2xl:px-10">
    <header data-erp-enter className="flex flex-col gap-5 border-b border-[#dce6e0] pb-6 xl:flex-row xl:items-center xl:justify-between"><div><h1 className="text-[2rem] font-semibold tracking-[-0.045em] text-[#10233f] sm:text-[2.35rem]">Visão operacional</h1><p className="mt-1 text-sm text-[#657284]">Acompanhamento em tempo real da operação.</p></div><div className="flex flex-wrap items-center gap-3"><button type="button" className="inline-flex min-h-11 items-center gap-2 rounded-lg border border-[#cfd8df] bg-white px-4 text-sm font-medium text-[#20324b]"><CalendarDays size={17} /> {formattedToday}</button><button type="button" className="inline-flex min-h-11 items-center gap-2 rounded-lg border border-[#cfd8df] bg-white px-4 text-sm font-medium text-[#20324b]">{obras.find(item => item.status === 'Ativa')?.nome || 'Todas as operações'} <ChevronDown size={16} className="ml-3" /></button><span className="inline-flex min-h-11 items-center gap-2 px-2 text-sm text-[#66756d]"><RefreshCw size={16} className="text-[#087345]" /> Atualizado agora</span></div></header>
    <section aria-label="Indicadores principais" className="mt-6 grid gap-4 sm:grid-cols-2 2xl:grid-cols-4">{metrics.map(metric => { const Icon = metric.icon; return <article data-erp-enter key={metric.label} className="flex min-h-[158px] items-center gap-5 rounded-xl border border-[#dfe5e9] bg-white p-5 shadow-[0_5px_16px_rgba(26,48,67,.055)] 2xl:p-6"><span className="grid h-14 w-14 shrink-0 place-items-center rounded-full bg-[#eaf4ee] text-[#07643d]"><Icon size={25} strokeWidth={1.9} /></span><div className="min-w-0"><p className="text-[14px] font-medium text-[#506078]">{metric.label}</p><p className="mt-1 text-[2rem] font-semibold tracking-[-0.045em] text-[#08663f]">{metric.value}</p><p className="mt-1 truncate text-xs text-[#718077]">{metric.note}</p></div></article>; })}</section>
    <section className="mt-6 grid gap-6 xl:grid-cols-12"><article data-erp-enter className="rounded-xl border border-[#dfe8e3] bg-white p-5 shadow-[0_8px_24px_rgba(24,54,39,.04)] xl:col-span-7 xl:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-lg font-semibold tracking-[-0.025em] text-[#132b20]">Atenção operacional</p><p className="mt-1 text-sm text-[#738278]">Itens que requerem uma ação imediata da gestão.</p></div><button type="button" onClick={() => setShowDetails(value => !value)} className="inline-flex items-center gap-1 text-sm font-semibold text-[#087345] hover:text-[#054a2d]">{showDetails ? 'Ocultar itens' : `Ver todos${alerts.length ? ` (${alerts.length})` : ''}`} <ChevronDown className={showDetails ? 'rotate-180 transition-transform' : 'transition-transform'} size={16} /></button></div><div className="mt-6 space-y-2.5">{alerts.length ? alerts.slice(0, showDetails ? alerts.length : 3).map(alert => { const tone = alert.tone === 'danger' ? 'border-l-[#e14d58] bg-[#fffafb] text-[#ba3d4d] border-[#f3d9dd]' : alert.tone === 'warning' ? 'border-l-[#ef9b16] bg-[#fffdf8] text-[#b56b00] border-[#f4e5c9]' : alert.tone === 'info' ? 'border-l-[#347bc0] bg-[#fbfdff] text-[#286eaa] border-[#d9e7f5]' : 'border-l-[#74867c] bg-[#fbfcfb] text-[#52645a] border-[#e1e8e3]'; return <button key={alert.id} type="button" onClick={() => onNavigate(alert.tab)} className={`group flex w-full items-center gap-4 rounded-lg border border-l-4 px-4 py-3.5 text-left transition hover:-translate-y-px hover:shadow-sm ${tone}`}><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-white/80">{alert.tone === 'danger' ? <ShieldAlert size={19} /> : <AlertTriangle size={19} />}</span><span className="min-w-0 flex-1"><span className="block text-sm font-semibold text-[#263b30]">{alert.title}</span><span className="mt-1 block truncate text-xs text-[#6e7e75]">{alert.detail}</span></span><span className="grid h-8 min-w-8 place-items-center rounded-md border border-current/30 bg-white/70 px-2 text-sm font-bold">{alert.badge}</span><ChevronRight className="shrink-0 text-[#7a8a81] transition group-hover:translate-x-0.5" size={18} /></button>; }) : <div className="flex items-center gap-3 rounded-lg border border-[#dce9df] bg-[#f8fcf9] px-4 py-6 text-sm text-[#3e6950]"><span className="grid h-10 w-10 place-items-center rounded-full bg-[#e8f5ec] text-[#087345]"><ClipboardCheck size={19} /></span>Nenhuma pendência crítica identificada.</div>}</div></article>
      <article data-erp-enter className="rounded-xl border border-[#dfe8e3] bg-white p-5 shadow-[0_8px_24px_rgba(24,54,39,.04)] xl:col-span-5 xl:p-6"><div className="flex gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#e9f5ed] text-[#087345]"><Truck size={20} /></span><div><p className="text-lg font-semibold tracking-[-0.025em] text-[#132b20]">Disponibilidade da frota</p><p className="mt-1 text-sm text-[#738278]">Panorama geral de disponibilidade.</p></div></div><div className="mt-8"><div className="flex items-end justify-between"><strong className="text-6xl font-semibold tracking-[-0.07em] text-[#087345]">{equipmentAvailability}<span className="text-3xl">%</span></strong><span className="mb-2 text-sm font-medium text-[#4c705e]">{overview.active} ativos</span></div><p className="mt-1 text-sm text-[#63776b]">Disponibilidade geral</p><div className="mt-4 h-3 overflow-hidden rounded-full bg-[#e1ebe5]"><div className="h-full rounded-full bg-[#087345]" style={{ width: `${equipmentAvailability}%` }} /></div></div><dl className="mt-7 divide-y divide-[#e7eee9] border-y border-[#e7eee9] text-sm"><div className="flex items-center justify-between py-3"><dt className="flex items-center gap-2 text-[#607167]"><span className="h-2.5 w-2.5 rounded-full bg-[#087345]" />Em operação</dt><dd className="font-semibold text-[#233b2e]">{overview.active}</dd></div><div className="flex items-center justify-between py-3"><dt className="flex items-center gap-2 text-[#607167]"><span className="h-2.5 w-2.5 rounded-full bg-[#91ca9e]" />À disposição</dt><dd className="font-semibold text-[#233b2e]">{overview.available}</dd></div><div className="flex items-center justify-between py-3"><dt className="flex items-center gap-2 text-[#607167]"><span className="h-2.5 w-2.5 rounded-full bg-[#f3b62d]" />Em manutenção</dt><dd className="font-semibold text-[#233b2e]">{overview.maintenance}</dd></div></dl></article></section>
    <section className="mt-6 grid gap-6 xl:grid-cols-12"><article data-erp-enter className="rounded-xl border border-[#dfe8e3] bg-white p-5 shadow-[0_8px_24px_rgba(24,54,39,.04)] xl:col-span-8 xl:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-lg font-semibold tracking-[-0.025em] text-[#132b20]">Consumo por equipamento</p><p className="mt-1 text-sm text-[#738278]">Distribuição dos maiores volumes no período.</p></div><button type="button" onClick={() => onNavigate('lancamentos')} className="inline-flex items-center gap-1 text-sm font-semibold text-[#087345] hover:text-[#054a2d]">Ver detalhes <ChevronRight size={16} /></button></div><div className="mt-6"><div className="mb-3 grid grid-cols-[minmax(0,1fr)_auto] gap-4 border-b border-[#e5ece7] pb-2 text-[11px] font-semibold uppercase tracking-[.08em] text-[#7d8b83]"><span>Equipamento</span><span>Litros (L)</span></div>{overview.fuelByFleet.length ? <div className="space-y-4">{overview.fuelByFleet.map((item, index) => { const percentage = overview.fuelByFleet[0]?.liters ? Math.max(7, (item.liters / overview.fuelByFleet[0].liters) * 100) : 0; return <div key={item.prefix} className="grid grid-cols-[minmax(0,1fr)_auto] items-center gap-4"><div className="min-w-0"><div className="flex items-center gap-2"><span className="grid h-8 w-8 place-items-center rounded-lg bg-[#edf6ef] text-[#087345]"><Droplets size={15} /></span><span className="truncate text-sm font-semibold text-[#263d30]">{item.prefix} <span className="font-normal text-[#77877e]">· {item.name}</span></span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-[#edf2ee]"><div className="h-full rounded-full" style={{ width: `${percentage}%`, background: index === 0 ? '#087345' : '#80b298' }} /></div></div><span className="text-sm font-semibold text-[#1e4933]">{formatLiters.format(item.liters)}</span></div>; })}</div> : <p className="rounded-lg border border-dashed border-[#cbd8cf] px-4 py-9 text-center text-sm text-[#738177]">Ainda não há consumo operacional registrado.</p>}</div></article>
      <article data-erp-enter className="rounded-xl border border-[#dfe8e3] bg-white p-5 shadow-[0_8px_24px_rgba(24,54,39,.04)] xl:col-span-4 xl:p-6"><div className="flex items-start justify-between gap-3"><div><p className="text-lg font-semibold tracking-[-0.025em] text-[#132b20]">Atividade recente</p><p className="mt-1 text-sm text-[#738278]">Últimos eventos registrados.</p></div><Clock3 className="text-[#087345]" size={20} /></div><ol className="mt-6 space-y-4 border-l border-[#d9e6de] pl-5">{historyLogs.slice(0, 5).map(event => <li key={event.id} className="relative"><span className="absolute -left-[1.62rem] top-1.5 h-3 w-3 rounded-full border-[3px] border-white bg-[#087345] shadow-[0_0_0_1px_#a6cbb4]" /><span className="block truncate text-sm font-semibold text-[#294032]">{event.acao}</span><span className="mt-1 block text-xs text-[#78877f]">{event.usuario || 'Operador'} · {event.timestamp}</span></li>)}{!historyLogs.length && <li className="-ml-2 rounded-lg border border-dashed border-[#cbd8cf] px-4 py-7 text-center text-sm text-[#738177]">As ações realizadas aparecerão aqui.</li>}</ol></article></section>
    <section data-erp-enter className="mt-6 overflow-hidden rounded-xl border border-[#dfe8e3] bg-white shadow-[0_8px_24px_rgba(24,54,39,.04)]"><div className="grid divide-y divide-[#e2eae5] md:grid-cols-3 md:divide-x md:divide-y-0">{[['Controle de frotas', 'Acompanhe situação e utilização dos equipamentos.', 'controle-equipamentos', Truck], ['Presença por equipe', 'Registre e acompanhe as equipes em campo.', 'presenca', Users], ['Relatórios operacionais', 'Acesse indicadores e relatórios para decisão.', 'reports', ClipboardCheck]].map(([label, detail, tab, Icon]) => { const ActionIcon = Icon as typeof Truck; return <button key={tab as string} type="button" onClick={() => onNavigate(tab as string)} className="group flex min-h-[122px] items-center gap-4 px-5 py-5 text-left transition hover:bg-[#f6faf7] xl:px-6"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-xl bg-[#075f3a] text-white shadow-[0_5px_12px_rgba(6,95,58,.16)]"><ActionIcon size={23} /></span><span className="min-w-0 flex-1"><span className="block text-sm font-semibold text-[#203a2c]">{label as string}</span><span className="mt-1 block text-xs leading-5 text-[#718178]">{detail as string}</span></span><ChevronRight className="shrink-0 text-[#6d7e74] transition group-hover:translate-x-0.5" size={19} /></button>; })}</div></section>
  </div>;
}
